### ISSUE TITLE
Need help from you

### ISSUE THREAD

**Issue by vinayshashtri** [TeodorKolev/c-tasks#1]
Hi brother, sorry to message you over here, because I have no way to message you

Do you have solution of below issue?

https://github.com/chthai64/SwipeRevealLayout/issues/53

Then please message me, I need it urgent

**Comment by hydrated** [comment]
@vinayshashtri Hi, I already merge my feature branch into my master branch, So you can find usage and demo here

https://github.com/hydrated/SwipeRevealLayout/

**Comment by TeodorKolev** [comment]
@vinayshashtri Yes, I have start using https://github.com/rambler-digital-solutions/swipe-layout-android
